In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)
a

array([ 0.20857469, -0.30992279, -1.38182883,  0.00620179, -0.98516526])

In [3]:
#Rank 1 array- 
a.shape

(5,)

In [4]:
a.T

array([ 0.20857469, -0.30992279, -1.38182883,  0.00620179, -0.98516526])

In [5]:
np.dot(a,a.T)

3.019595517230448

In [6]:
#Redo the same process
a = np.random.randn(5,1)
a

array([[ 0.31013262],
       [-0.14748188],
       [-0.02891613],
       [-0.87456624],
       [ 0.0464    ]])

In [7]:
a.shape

(5, 1)

In [8]:
a.T

array([[ 0.31013262, -0.14748188, -0.02891613, -0.87456624,  0.0464    ]])

In [9]:
np.dot(a,a.T)

array([[ 0.09618224, -0.04573894, -0.00896784, -0.27123152,  0.01439015],
       [-0.04573894,  0.0217509 ,  0.00426461,  0.12898267, -0.00684316],
       [-0.00896784,  0.00426461,  0.00083614,  0.02528907, -0.00134171],
       [-0.27123152,  0.12898267,  0.02528907,  0.7648661 , -0.04057987],
       [ 0.01439015, -0.00684316, -0.00134171, -0.04057987,  0.00215296]])

In [10]:
a= np.random.randn(1,5)

In [11]:
a= np.random.rand(8,1)
a

array([[0.60370484],
       [0.65801223],
       [0.10442283],
       [0.47635992],
       [0.79200477],
       [0.93258525],
       [0.89520137],
       [0.9558125 ]])

In [12]:
a.shape

(8, 1)

In [17]:
a.reshape(2,2,2)

array([[[0.60370484, 0.65801223],
        [0.10442283, 0.47635992]],

       [[0.79200477, 0.93258525],
        [0.89520137, 0.9558125 ]]])

In [28]:
#Consider the following random arrays aa and bb, and cc:

a=np.random.randn(2, 3)

b=np.random.randn(2,1) 
print(a)
print(b)

[[ 2.14011283 -0.09480043  0.17866181]
 [ 0.56072648  0.27120007  0.7188124 ]]
[[0.68788571]
 [0.34777233]]


In [30]:
c= a+b
c.shape

(2, 3)

In [21]:
#Consider the two following random arrays aa and bb:
    
a=np.random.randn(4,3) 

b = np.random.randn(3, 2)

print(a)

print(b)

[[-1.76157842  0.31310149  0.2147055 ]
 [ 0.48332431  1.70077928  0.43781702]
 [-0.80634787  0.42608085  1.0561017 ]
 [ 1.24242421  1.47888644 -1.67140801]]
[[-0.66969297 -0.06027089]
 [ 0.33180829  0.50424106]
 [ 1.25819963  1.36833951]]


In [24]:
c = a*b
c.shape

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [34]:
a=np.random.randn(3,4) 

b = np.random.randn(1,4)
c= a+b
c.shape

(3, 4)

In [35]:
a=np.random.randn(4,3) 

b = np.random.randn(1,3)
c= a*b
c.shape

(4, 3)

In [26]:
a=np.random.randn(12288,150) 
b=np.random.randn(150,45) 

c=np.dot(a,b) 
print(c)
print(c.shape)

[[  6.98752377   5.79613037  -7.51439918 ... -11.87110729  -8.19566523
   17.17694181]
 [ 21.09261146  11.61237404  15.92730901 ...  20.7093983  -13.21341252
  -16.60606025]
 [ 14.22986942  -2.26062088  11.11901563 ...  -6.60812844   8.61279406
   16.85721172]
 ...
 [ 17.44241335  15.35430364   6.4314354  ...   3.56618891 -28.70899124
  -10.95049246]
 [  9.11349297 -10.99995245 -11.26131153 ...   1.09328249 -22.29691007
    0.73283824]
 [ -5.18440335 -20.24198252  -5.11521097 ...  14.86491022  11.52190172
   -3.35876438]]
(12288, 45)


In [27]:
a = np.array([[1,1],[1,-1]])
b = np.array([[2],[3]])
c=a+b
c

array([[3, 3],
       [4, 2]])

In [31]:
a = np.array([[2,1],[1,3]])
a*a

array([[4, 1],
       [1, 9]])

## Observation: 
### Do not use Rank 1 array
### use reshape operation to change the reshape Rank 1 array

In [2]:
import numpy as np
x = np.random.rand(3, 2)

y = np.sum(x, axis=0, keepdims=True)

In [3]:
y.shape

(1, 2)

In [4]:
x

array([[0.82555678, 0.47779224],
       [0.65933949, 0.97372289],
       [0.59137886, 0.71112656]])

In [5]:
y

array([[2.07627512, 2.16264169]])

In [6]:
x = np.random.rand(4,5)

y = np.sum(x, axis=0,)

In [7]:
y.shape

(5,)